### ISSUE TITLE
“This code is valid for 30 minutes” should be "This verification email is valid for 30 minutes"

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-auth-shared#23]
https://github.com/pxblue/react-auth-shared/blob/dev/src/data/translations/english.ts#L76 

This is wrong. How can you have only the code expire, but not the link?

**Comment by andrupu** [comment]
Let's talk with PX White and see how they handle this (Confirm expiration time and API).

**Comment by joebochill** [comment]
Executive decision on this one...the Link is valid, the code is not. Closing this issue.

If you click the link and it takes you somewhere, the link is valid. If you get a 404, the link is invalid.
