### ISSUE TITLE
“There was an error with your reset code.” -> ""Your Reset Password link is invalid."

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-auth-shared#24]
For the end user, they would have no idea what a "reset code" is. 

In [the translation](https://github.com/pxblue/react-auth-shared/blob/dev/src/data/translations/english.ts#L91), change `FORGOT_PASSWORD.RESET_CODE_ERROR` to “There was an error with your reset code.” -> "Your Reset Password link is invalid."

**Comment by andrupu** [comment]
We can get the text re-worded in Angular as well as (Don't forget the Human Languages: Spanish, French, Chinese, etc.)

**Comment by joebochill** [comment]
Executive decision on this one...the Link is valid, the code is not. Closing this issue.
