### ISSUE TITLE
API Docs Need Update for registrationSuccessScreen

### ISSUE THREAD

**Issue by misskaseyann** [brightlayer-ui/react-auth-shared#39]
#### Describe the bug
[API documentation](https://github.com/pxblue/react-auth-shared/blob/master/docs/API.md) seems to be out of date in regards to the `AuthUIContextProvider`.

As stated:
> registrationSuccessScreen: (optional) JSX.Element | (navigation: any, registrationData?: RegistrationData) => JSX.Element | (registrationData?: RegistrationData) => JSX.Element

However, in the code, it looks like all that is passed along is `registrationData` (in both `InviteRegistrationPager.tsx` and `SelfRegistrationPager.tsx` and there is no option where the navigation is being passed along:
```
// Custom Success Screen
    else if (isLastStep && !accountAlreadyExists && validationSuccess && !isValidationInTransit && customSuccess) {
        return (
            <BrandedCardContainer loading={registrationIsInTransit || isValidationInTransit || codeRequestIsInTransit}>
                {typeof customSuccess === 'function' && customSuccess({ accountDetails: accountDetails })}
                {typeof customSuccess !== 'function' && customSuccess}
            </BrandedCardContainer>
        );
    }
```

#### What is the expected behavior?
Have updated documentation to reflect production code.

#### What are the steps to reproduce?
N/A

#### Screenshots or links to minimum reproduction example
N/A

#### Environment

N/A

**Comment by misskaseyann** [comment]
Thank you so much for the update @joebochill 
Our team is currently using the React workflow and we were a bit thrown off by the types and what we were actually getting. It is good to have that extra clarity as to why that navigation portion was there. :)

**Comment by joebochill** [comment]
We have a new version of the shared auth package going out (hopefully this week) - I’ve bundled in an update to the api docs that adds a bullet point explaining that the type with the navigation object is a react native exclusive. Hopefully that will help clarify things.
