### ISSUE TITLE
More Details about how to the use the loginErrorDisplayConfig

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/react-auth-shared#46]
#### Describe the desired behavior
Add a comment or some additional information about how to use this property.  For example, the default error message of `LOGIN.INVALID_CREDENTIALS` doesn't work with this property enabled. 

#### Describe the current behavior
There's little information around this. 

#### Is this request related to a current issue?
No

**Comment by jeffvg** [comment]
for next sprint
