### ISSUE TITLE
Fix <b>unbolded</b> text on Forgot Password Page

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/react-auth-shared#59]
#### Describe the bug
Portuguese Translation has a bold tag that isn't rendering property.

#### What is the expected behavior?
It's bolded.

#### What are the steps to reproduce?
Run demo project using latest deps & observe.

#### Screenshots or links to minimum reproduction example
<img width="516" alt="Screen Shot 2021-12-17 at 11 10 44 AM" src="https://user-images.githubusercontent.com/6538289/146574419-2950b152-fc91-4095-8edb-f24c9465ac93.png">

**Comment by jeffvg** [comment]
This PR fixed bold issue https://github.com/brightlayer-ui/react-auth-shared/pull/63
